### ISSUE TITLE
点历史记录中的条目崩溃

### ISSUE THREAD

**Issue by bestchangge** [renjianan/SimpleBrowser#5]

**Comment by renjianan** [comment]
报什么错？

**Comment by bestchangge** [comment]
01-24 17:40:30.943 28148-28148/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.renny.simplebrowser, PID: 28148
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
                                                       at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:200)
                                                       at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:171)
                                                       at com.renny.simplebrowser.view.page.dialog.HistoryDialogFragment$5.onStateChanged(HistoryDialogFragment.java:137)
                                                       at android.support.design.widget.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:576)
                                                       at android.support.design.widget.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:760)
                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:157)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
